# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3c2ebc97dc10c6d4b2b0a0226917cc8d31689f932d794e664d50c493a49bcd80712345579453fcfb05ebc95d3a4f0b515f3535bbdd636706373c846ee024f7f

test:
  secret_key_base: be54e062091c225e64962628cda40a342c8bf34bd2d4de961f684832bdff27fbf02efaf3d1b04c565eecbb33329c9da18f7b385b732c7b5954ab0bea34160a3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
